[package]
name = "folders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
human-sort = "0.2.2"
clap = { version = "4.4.18", features = ["derive"] }
